name: Generate M3U8 Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    permissions:
      contents: write # КРИТИЧЕСКИ ВАЖНО ДЛЯ СОЗДАНИЯ ВЕТКИ
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Stream Script
        run: |
          mkdir -p hls
          python stream.py
          # Скрипт должен поработать минут 5 и завершиться сам, 
          # чтобы файлы сохранились в папку hls

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: hls
          branch: gh-pages
